name: Trigger Blog Rebuild

on:
  push:
    branches:
      - main # Körs endast när ändringar pushas till main-branchen
    paths:
      - '**.md' # Triggar endast för markdown-filer
      - '**.mdx' # Och MDX-filer

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blog rebuild
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.BLOG_DEPLOY_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/SemuraiAB/semurai-dev-blog/dispatches \
          -d '{"event_type": "blog_content_update", "client_payload": {"user_name": "${{ github.actor }}", "user_email": "${{ github.event.pusher.email }}"} }'
